[package]
name = "generate-excel"
version = "0.1.0"
authors = ["eflorespalma <eflorespalma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_excel_writer="0.1.4"